[package]
name = "function"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["cdylib"]

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = true


[dependencies]
axum = { version = "0.8.1", default-features = false }
cap-async-std = "3.4.2"

