[package]
name = "cargo-faasta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow.workspace = true
tokio.workspace = true
serde_json.workspace = true
zip.workspace = true
reqwest = { version = "0.12.12", features = ["blocking","stream","multipart","json"] }
walkdir = "2.5.0"
faasta-analyze = { path = "../analyze" }
clap = { version = "4", features = ["derive"] }
clap-cargo = "0.15.1"
