[package]
name = "cargo-faasta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.95"
tokio = { version = "1.42", features = ["macros", "rt-multi-thread", "rt"] }
reqwest = { version = "0.12.12", features = ["blocking","stream","multipart","json"] }
walkdir = "2.5.0"
serde_json = "1.0.134"
zip = "2.2.2"
faasta-analyze = { path = "../analyze" }
clap = { version = "4.5.23", features = ["derive"] }
clap-cargo = "0.15.1"
