[package]
name = "faasproc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.31"
anyhow = "1.0.95"
tokio = { version = "1.42", features = ["macros", "rt-multi-thread", "rt"] }
reqwest = { version = "0.12.12", features = ["blocking","stream","multipart","json"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
geiger = "0.4.12"
walkdir = "2.5.0"
serde_json = "1.0.134"
zip = "2.2.2"
analyze = { path = "../analyze" }
clap = { version = "4.5.23", features = ["derive"] }
clap-cargo = "0.15.1"
