[package]
name = "faasta-analyze"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full", "visit"] }
quote = "1.0"
tokio = { version = "1.42.0", features = ["full"] }
anyhow = "1.0"
geiger = "0.4.12"
lazy_static = "1.5.0"
toml = "0.8.19"
log = "0.4.22"