[package]
name = "rustfaas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
tokio = { version = "1.42", features = ["macros", "fs", "rt-multi-thread", "process", "io-util"] }
futures = { version = "0.3.31", default-features = false }
bytes = "1.0"
libloading = "0.8.6"
multipart = "0.18"
tower-http = {version = "*", features = ["catch-panic"]}
zip = "2.2.2"
axum = { version = "0.8.1", features = ["multipart"] }
tower = { version = "*", features = ["timeout"] }
geiger = "0.4.12"
http = "1.2.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
sha2 = "0.10.8"
chashmap = "2.2.2"
lazy_static = "1.5.0"
async-scoped = { version = "0.9.0", features = ["use-tokio"] }
uuid = { version = "1.11.0", features = ["v4"] }
tokio-util = { version = "0.7.13", features = ["io-util"] }
anyhow = "1.0.95"
toml = "0.8.19"
hmac = "0.12.1"
hex = "0.4.3"
faasta-analyze = { path = "../analyze" }
cap-async-std = { version = "3.4.2", features = ["tokio1"] }
async-std = { version = "1.13.0", features = ["tokio1"] }
