#cargo-features = ["codegen-backend"]

[package]
name = "faasta"
version = "0.1.0"
edition = "2021"

#[unstable]
#codegen-backend = true

#[profile.dev]
#codegen-backend = "cranelift"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
zip.workspace = true
futures = { version = "0.3.31", default-features = false }
libloading = "0.8.6"
tower-http = {version = "0.6", features = ["catch-panic"]}
axum = { version = "0.8.1", features = ["multipart", "macros"] }
tower = { version = "0.5", features = ["timeout"] }
http = "1"
serde = { version = "1", features = ["derive"] }
blake3 = "1"
lazy_static = "1"
async-scoped = { version = "0.9.0", features = ["use-tokio"] }
tokio-util = { version = "0.7.13", features = ["io-util"] }
faasta-analyze = { path = "../analyze" }
cap-async-std = { version = "3.4.2", features = ["tokio1"] }
dashmap = "6"
