[package]
name = "faas-proc-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.38"
syn = { version = "2.0.95", features = ["full", "visit"] }
hmac = "0.13.0-pre.4"
sha2 = "0.11.0-pre.4"
hex = "0.4.3"

[lib]
proc-macro = true
