[package]
name = "faasta-macros"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Proc macros for Faasta"

[dependencies]
quote = "1"
syn = { version = "2", features = ["full", "visit"] }
blake3 = "1"

[lib]
proc-macro = true

